# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,QtSvg
import os
import sys
import astronomy as a
full_evt_data = []
full_sum_energy = 0
start_week = 0
end_week = 0
full_weights = []   
svg_Figure=[]
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.index=0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.viewer = QtWidgets.QScrollArea(self.centralwidget)
        self.viewer.setGeometry(QtCore.QRect(40, 100, 731, 431))
        self.viewer.setWidgetResizable(True)
        self.viewer.setObjectName("viewer")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 729, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.viewer.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 681, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.submit.setObjectName("submit")
        self.horizontalLayout.addWidget(self.submit)
        self.next_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_pushButton.setGeometry(QtCore.QRect(530, 560, 93, 28))
        self.next_pushButton.setObjectName("next_pushButton")
        self.back_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.back_pushButton.setGeometry(QtCore.QRect(140, 560, 93, 28))
        self.back_pushButton.setObjectName("back_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.submit.clicked.connect(self.submit_method)
        self.next_pushButton.clicked.connect(self.next_method)
        self.back_pushButton.clicked.connect(self.back_method)
    def submit_method(self):
        start_week = int(self.lineEdit.text())
        end_week = int(self.lineEdit_2.text())
        start_eng_range=int(self.lineEdit_3.text())
        end_eng_range=int(self.lineEdit_4.text())
        a.download_some_files(start_week,end_week)
        
        try:
            if a.os.path.isdir(str(a.Path().absolute()) + f"\\outputs\\"):
                pass
            else:
                a.os.makedirs(str(a.Path().absolute()) + f"\\outputs\\")
        except:
            print("Raised Exception")
        a.procedural_gen_full(start_week, end_week, start_eng_range, end_eng_range)
        self.save_svg_file()
        self.show()
    #def file(self):
    def save_svg_file(self):
        for path, dirs, files in os.walk(os.path.abspath("outputs")):
            for file in files:
                filePath= os.path.join(path,file)
                svgWidget=QtSvg.QSvgWidget(filePath)
                svg_Figure.append(svgWidget)
    def back_method(self):
        self.index-=1
        self.show()
    def next_method(self):
        self.index+=1
        self.show()
    def show(self):
        figure=svg_Figure[self.index]
        self.viewer.setWidget(figure)
        figure.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Start week"))
        self.label_2.setText(_translate("MainWindow", "End week"))
        self.label_3.setText(_translate("MainWindow", "low eng"))
        self.label_4.setText(_translate("MainWindow", "high eng"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.next_pushButton.setText(_translate("MainWindow", "next"))
        self.back_pushButton.setText(_translate("MainWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
